use serde::Deserialize;
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use crate::error::RwalError;
use crate::paths::Paths;
use crate::colors::semantic::SemanticDict;

/// The top-level mapping file (~/.config/rwal/theme-map.toml)
#[derive(Deserialize, Debug)]
pub struct ThemeMap(pub HashMap<String, AppEntry>);

/// A single application's config mapping entry
#[derive(Deserialize, Debug)]
pub struct AppEntry {
    /// Where to write the generated config (supports ~/)
    pub output: String,
    /// Format: toml | css | ini (fallback: key = value)
    pub format: Option<String>,
    /// Map of [app-specific-key] = "semantic-role"
    pub map: HashMap<String, String>,
}

/// Render ALL apps defined in theme-map.toml using the active semantic palette.
pub fn render_all(paths: &Paths, semantic: &SemanticDict) -> Result<(), RwalError> {
    let theme_map = load_theme_map(paths)?;
    
    for (name, app) in theme_map.0 {
        if let Err(e) = render_app(&name, &app, semantic) {
            crate::error::warn(&e);
        }
    }
    
    Ok(())
}

/// Render a single named app from the mapping file.
pub fn render_one(paths: &Paths, semantic: &SemanticDict, name: &str) -> Result<(), RwalError> {
    let theme_map = load_theme_map(paths)?;
    let app = theme_map.0.get(name)
        .ok_or_else(|| RwalError::Custom(format!("app '{}' not found in theme-map.toml", name)))?;
    
    render_app(name, app, semantic)
}

fn load_theme_map(paths: &Paths) -> Result<ThemeMap, RwalError> {
    if !paths.theme_map.exists() {
        return Err(RwalError::Custom("theme-map.toml not found. Run rwal once to seed it.".into()));
    }

    let content = std::fs::read_to_string(&paths.theme_map)
        .map_err(|e| RwalError::CacheReadError(paths.theme_map.clone(), e.to_string()))?;

    let map: ThemeMap = toml::from_str(&content)
        .map_err(|e| RwalError::Custom(format!("failed to parse theme-map.toml: {}", e)))?;

    Ok(map)
}

fn render_app(name: &str, app: &AppEntry, semantic: &SemanticDict) -> Result<(), RwalError> {
    let output_path = resolve_path(&app.output);
    
    // Ensure parent directory exists
    if let Some(parent) = output_path.parent() {
        if !parent.exists() {
            std::fs::create_dir_all(parent)
                .map_err(|e| RwalError::CreateDirFailed(parent.to_path_buf(), e.to_string()))?;
        }
    }

    let format = app.format.as_deref().unwrap_or("conf");
    let mut content = format!("# Generated by rwal for {} from {}\n", name, semantic.wallpaper);
    
    // Sort keys for deterministic output
    let mut keys: Vec<_> = app.map.keys().collect();
    keys.sort();

    for key in keys {
        let role = &app.map[key];
        
        // Lookup the color in the semantic palette
        // Check both .colors and .special
        let color = match role.as_str() {
            "background" => Some(&semantic.colors.background),
            "surface"    => Some(&semantic.colors.surface),
            "foreground" => Some(&semantic.colors.foreground),
            "cursor"     => Some(&semantic.colors.cursor),
            "primary"    => Some(&semantic.colors.primary),
            "secondary"  => Some(&semantic.colors.secondary),
            "tertiary"   => Some(&semantic.colors.tertiary),
            "accent"     => Some(&semantic.colors.accent),
            "error"      => Some(&semantic.colors.error),
            "success"    => Some(&semantic.colors.success),
            "warning"    => Some(&semantic.colors.warning),
            "info"       => Some(&semantic.colors.info),
            "neutral"    => Some(&semantic.colors.neutral),
            "neutral_variant" => Some(&semantic.colors.neutral_variant),
            "on_background"   => Some(&semantic.colors.on_background),
            "on_primary"      => Some(&semantic.colors.on_primary),
            "on_surface"      => Some(&semantic.colors.on_surface),
            // Special roles
            "special.background" => Some(&semantic.special.background),
            "special.foreground" => Some(&semantic.special.foreground),
            "special.cursor"     => Some(&semantic.special.cursor),
            _ => None,
        };

        let color = match color {
            Some(c) => c,
            None => {
                crate::error::warn(&RwalError::Custom(format!("role '{}' not found in semantic palette", role)));
                continue;
            }
        };

        match format {
            "toml" => {
                content.push_str(&format!("{} = \"{}\"\n", key, color));
            }
            "css" => {
                // convert key.with.dots to key-with-dots for CSS variables
                let css_key = key.replace('.', "-");
                content.push_str(&format!("  --{}: {};\n", css_key, color));
            }
            "ini" | "conf" => {
                content.push_str(&format!("{} = {}\n", key, color));
            }
            _ => {
                content.push_str(&format!("{} = {}\n", key, color));
            }
        }
    }

    std::fs::write(&output_path, content)
        .map_err(|e| RwalError::Custom(format!("failed to write config to {}: {}", output_path.display(), e)))?;

    Ok(())
}

fn resolve_path(path: &str) -> PathBuf {
    if path.starts_with("~/") {
        if let Some(home) = dirs::home_dir() {
            return home.join(&path[2..]);
        }
    }
    PathBuf::from(path)
}
