# colors_tty.sh — generated by rwal
# Source this file or run it to apply colors to the Linux TTY.
# Only has effect on a real TTY (not a terminal emulator).

if [ "$TERM" = "linux" ]; then
    printf '\e]P0{color0}'   # black
    printf '\e]P1{color1}'   # red
    printf '\e]P2{color2}'   # green
    printf '\e]P3{color3}'   # yellow
    printf '\e]P4{color4}'   # blue
    printf '\e]P5{color5}'   # magenta
    printf '\e]P6{color6}'   # cyan
    printf '\e]P7{color7}'   # white
    printf '\e]P8{color8}'   # bright black
    printf '\e]P9{color9}'   # bright red
    printf '\e]PA{color10}'  # bright green
    printf '\e]PB{color11}'  # bright yellow
    printf '\e]PC{color12}'  # bright blue
    printf '\e]PD{color13}'  # bright magenta
    printf '\e]PE{color14}'  # bright cyan
    printf '\e]PF{color15}'  # bright white
    clear                    # flush color artifacts
fi